
exports.block  = Symbol('block')
exports.if     = Symbol('if')
exports.and    = Symbol('and')
exports.or     = Symbol('or')
exports.loop   = Symbol('loop')
exports.fun    = Symbol('fun')
exports.mac    = Symbol('mac')
exports.def    = Symbol('def')
exports.set    = Symbol('set')
exports.export = Symbol('export')
exports.import = Symbol('import')
exports.module = Symbol('module')
exports.get    = Symbol('get')
exports.quote  = Symbol('quote')
exports.unquote  = Symbol('unquote')
